---
title: "Notes"
author: "GL Li"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Census 2000
### reference is one digit shorter than that of 2010
For example, the total population is P001001 in census 2000, while P0010001 in 2010. To keep the consistency, add a "0" to those in census 2000.

### list of tables
P27H is mistaken as P28H. Corrected in the txt file.



## 20200926: combine data to reduce package size 
- Reason: after adding 2019 ACS 1 year data, the package size increased to 5.2 M, which is above the CRAN limit. 
- Solution: combine data `lookup_acs1year_2019`, `lookup_acs1year_2018`, ... .... The original data has columns `file_segment`,  `table_content` `reference`, `restriction`, `table_number`, `table_name`, `universe`. Many are the same across data. To reduce the total size: 
    - keep columns `file_segment`, table_content`, and `reference` for each file.
    - merge columns `reference`, `restriction`, `table_number`, `table_name`, and `universe` into a seperate table.
